language: go
go:
 - 1.5.x
 - 1.6.x
 - 1.7.x
 - 1.8.x
 - 1.9.x
 - 1.10.x
 - 1.11.x
 - 1.12.x
 - master

addons:
  apt:
    packages:
      libpcap-dev

# 1.5 and 1.6 need special handling (see .travis.install.sh)
install: ./.travis.install.sh

# 1.5 and 1.6 need special handling (see .travis.script.sh)
script: ./.travis.script.sh

matrix:
  fast_finish: true
  allow_failures:
    - go: master

jobs:
  include:
    - os: osx
      go: 1.x
    - os: windows
      go: 1.x
      before_install: choco install winpcap
    - stage: style
      name: "fmt/vet/lint"
      go: 1.x
      script:
        - ./.travis.gofmt.sh
        - ./.travis.govet.sh
        - ./.travis.golint.sh

stages:
  - style
  - test
