language: go
go:
 - 1.5.x
 - 1.6.x
 - 1.7.x
 - 1.8.x
 - 1.9.x
 - 1.10.x
 - 1.11.x
 - 1.12.x
 - master

addons:
  apt:
    packages:
      libpcap-dev

install:
 - go get github.com/google/gopacket
 - go get github.com/google/gopacket/layers
 - go get github.com/google/gopacket/pcapgo
 - go get github.com/google/gopacket/tcpassembly
 - go get github.com/google/gopacket/reassembly

script:
 - go test github.com/google/gopacket
 - go test github.com/google/gopacket/layers
 - go test github.com/google/gopacket/pcapgo 
 - go test github.com/google/gopacket/tcpassembly
 - go test github.com/google/gopacket/reassembly

matrix:
  fast_finish: true
  allow_failures:
    - go: master

jobs:
  include:
    - stage: style
      name: "fmt/vet/lint"
      go: 1.x
      script:
        - ./.travis.gofmt.sh
        - ./.travis.govet.sh
        - ./.travis.golint.sh

stages:
  - style
  - test
